apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend 
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend 
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: gihyodocker/nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: WORKER_PROCESSES
          value: "2"
        - name: WORKER_CONNECTIONS
          value: "1024"
        - name: LOG_STDOUT
          value: "true"
        - name: BACKEND_HOST
          value: "localhost:5000"
      - name: backend
        image: ruihirano/covid19-rader-for-japan-backend-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: KUBE_BACKEND_CALCULATOR_HOST
          value: "http://backend-calculator"
        - name: PORT
          value: "5000"
