package types

type DateSummary struct {
	Date       string `json:"date" csv:"日付"`
	Prefecture string `json:"prefecture" csv:"都道府県名"`
	Positives  string `json:"positives" csv:"陽性者"`
	Pcrs       string `json:"pcrs" csv:"検査人数"`
	Hospitals  string `json:"hospitals" csv:"入院中"`
	Severes    string `json:"severes" csv:"重症者"`
	Discharges string `json:"discharges" csv:"退院者"`
	Deaths     string `json:"deaths" csv:"死亡者"`
	Checking   string `json:"checking" csv:"確認中"`
	Class      string `json:"class" csv:"分類"`
}

type DateWorldSummary struct {
	Date            string `json:"date" csv:"date"`
	Update          string `json:"update" csv:"update"`
	Cases           string `json:"cases" csv:"cases"`
	NewCases        string `json:"new_cases" csv:"new_cases"`
	Deaths          string `json:"deaths" csv:"deaths"`
	Country         string `json:"country" csv:"country"`
	LastUpdate      string `json:"last_update" csv:"last_update"`
	Population      string `json:"population" csv:"population"`
	CasesPer100k    string `json:"casesPer100k" csv:"casesPer100k"`
	NewTests        string `json:"new_tests" csv:"new_tests"`
	TestsCumulative string `json:"tests_cumulative" csv:"tests_cumulative"`
	TestsPer100k    string `json:"testsPer100k" csv:"testsPer100k"`
	PositiveRate    string `json:"positiveRate" csv:"positiveRate"`
}

type News struct {
	//ID         string `json:"id" csv:"id"`
	Date       string `json:"date" csv:"date"`
	Title      string `json:"title" csv:"title"`
	Link       string `json:"link" csv:"link"`
	Prefecture string `json:"pre" csv:"pre"`
	Resident   string `json:"resident" csv:"resident"`
}

type DateCallcenter struct {
	Date string `json:"date" csv:"date"`
	Call string `json:"call" csv:"call"`
	Fax  string `json:"fax" csv:"fax"`
	Mail string `json:"mail" csv:"mail"`
	Line string `json:"line" csv:"line"`
}

// Finish
type DateDeathByPref struct {
	Date              string `json:"date" csv:"date"`
	Hokkaido          string `json:"hokkaido" csv:"北海道"`
	Aomori            string `json:"aomori" csv:"青森"`
	Iwate             string `json:"iwate" csv:"岩手"`
	Miyagi            string `json:"miyagi" csv:"宮城"`
	Akita             string `json:"akita" csv:"秋田"`
	Yamagata          string `json:"yamagata" csv:"山形"`
	Fukushima         string `json:"fukushima" csv:"福島"`
	Ibaraki           string `json:"ibaraki" csv:"茨城"`
	Tochigi           string `json:"tochigi" csv:"栃木"`
	Gunma             string `json:"gunma" csv:"群馬"`
	Saitama           string `json:"saitama" csv:"埼玉"`
	Chiba             string `json:"chiba" csv:"千葉"`
	Tokyo             string `json:"tokyo" csv:"東京"`
	Kanagawa          string `json:"kanagawa" csv:"神奈川"`
	Niigata           string `json:"niigata" csv:"新潟"`
	Toyama            string `json:"toyama" csv:"富山"`
	Ishikawa          string `json:"ishikawa" csv:"石川"`
	Fukui             string `json:"fukui" csv:"福井"`
	Yamanashi         string `json:"yamanashi" csv:"山梨"`
	Nagano            string `json:"nagano" csv:"長野"`
	Gifu              string `json:"gifu" csv:"岐阜"`
	Shizuoka          string `json:"shizuoka" csv:"静岡"`
	Aichi             string `json:"aichi" csv:"愛知"`
	Mie               string `json:"mie" csv:"三重"`
	Shiga             string `json:"shiga" csv:"滋賀"`
	Kyoto             string `json:"kyoto" csv:"京都"`
	Osaka             string `json:"osaka" csv:"大阪"`
	Hyogo             string `json:"hyogo" csv:"兵庫"`
	Nara              string `json:"nara" csv:"奈良"`
	Wakayama          string `json:"wakayama" csv:"和歌山"`
	Tottori           string `json:"tottori" csv:"鳥取"`
	Shimane           string `json:"shimane" csv:"島根"`
	Okayama           string `json:"okayama" csv:"岡山"`
	Hiroshima         string `json:"hiroshima" csv:"広島"`
	Yamaguchi         string `json:"yamaguchi" csv:"山口"`
	Tokushima         string `json:"tokushima" csv:"徳島"`
	Kagawa            string `json:"kagawa" csv:"香川"`
	Ehime             string `json:"ehime" csv:"愛媛"`
	Kochi             string `json:"kochi" csv:"高知"`
	Fukuoka           string `json:"fukuoka" csv:"福岡"`
	Saga              string `json:"saga" csv:"佐賀"`
	Nagasaki          string `json:"nagasaki" csv:"長崎"`
	Kumamoto          string `json:"kumamoto" csv:"熊本"`
	Oita              string `json:"oita" csv:"大分"`
	Miyazaki          string `json:"miyazaki" csv:"宮崎"`
	Kagoshima         string `json:"kagoshima" csv:"鹿児島"`
	Okinawa           string `json:"okinawa" csv:"沖縄"`
	Charter           string `json:"charter" csv:"チャーター便"`
	QuarantineOfficer string `json:"quarantine_officer" csv:"検疫職員"`
	Cruise            string `json:"cruise" csv:"クルーズ船"`
}

type DatePositiveByPref struct {
	Date              string `json:"date" csv:"date"`
	Hokkaido          string `json:"hokkaido" csv:"北海道"`
	Aomori            string `json:"aomori" csv:"青森"`
	Iwate             string `json:"iwate" csv:"岩手"`
	Miyagi            string `json:"miyagi" csv:"宮城"`
	Akita             string `json:"akita" csv:"秋田"`
	Yamagata          string `json:"yamagata" csv:"山形"`
	Fukushima         string `json:"fukushima" csv:"福島"`
	Ibaraki           string `json:"ibaraki" csv:"茨城"`
	Tochigi           string `json:"tochigi" csv:"栃木"`
	Gunma             string `json:"gunma" csv:"群馬"`
	Saitama           string `json:"saitama" csv:"埼玉"`
	Chiba             string `json:"chiba" csv:"千葉"`
	Tokyo             string `json:"tokyo" csv:"東京"`
	Kanagawa          string `json:"kanagawa" csv:"神奈川"`
	Niigata           string `json:"niigata" csv:"新潟"`
	Toyama            string `json:"toyama" csv:"富山"`
	Ishikawa          string `json:"ishikawa" csv:"石川"`
	Fukui             string `json:"fukui" csv:"福井"`
	Yamanashi         string `json:"yamanashi" csv:"山梨"`
	Nagano            string `json:"nagano" csv:"長野"`
	Gifu              string `json:"gifu" csv:"岐阜"`
	Shizuoka          string `json:"shizuoka" csv:"静岡"`
	Aichi             string `json:"aichi" csv:"愛知"`
	Mie               string `json:"mie" csv:"三重"`
	Shiga             string `json:"shiga" csv:"滋賀"`
	Kyoto             string `json:"kyoto" csv:"京都"`
	Osaka             string `json:"osaka" csv:"大阪"`
	Hyogo             string `json:"hyogo" csv:"兵庫"`
	Nara              string `json:"nara" csv:"奈良"`
	Wakayama          string `json:"wakayama" csv:"和歌山"`
	Tottori           string `json:"tottori" csv:"鳥取"`
	Shimane           string `json:"shimane" csv:"島根"`
	Okayama           string `json:"okayama" csv:"岡山"`
	Hiroshima         string `json:"hiroshima" csv:"広島"`
	Yamaguchi         string `json:"yamaguchi" csv:"山口"`
	Tokushima         string `json:"tokushima" csv:"徳島"`
	Kagawa            string `json:"kagawa" csv:"香川"`
	Ehime             string `json:"ehime" csv:"愛媛"`
	Kochi             string `json:"kochi" csv:"高知"`
	Fukuoka           string `json:"fukuoka" csv:"福岡"`
	Saga              string `json:"saga" csv:"佐賀"`
	Nagasaki          string `json:"nagasaki" csv:"長崎"`
	Kumamoto          string `json:"kumamoto" csv:"熊本"`
	Oita              string `json:"oita" csv:"大分"`
	Miyazaki          string `json:"miyazaki" csv:"宮崎"`
	Kagoshima         string `json:"kagoshima" csv:"鹿児島"`
	Okinawa           string `json:"okinawa" csv:"沖縄"`
	Charter           string `json:"charter" csv:"チャーター便"`
	QuarantineOfficer string `json:"quarantine_officer" csv:"検疫職員"`
	Cruise            string `json:"cruise" csv:"クルーズ船"`
}

type DateDetailByPref struct {
	Date                     string `json:"date" csv:"date"`
	Tests                    string `json:"tests" csv:"tests"`
	Confirmed                string `json:"confirmed" csv:"confirmed"`
	Deaths                   string `json:"deaths" csv:"deaths"`
	Recovered                string `json:"recovered" csv:"recovered"`
	Hosp                     string `json:"hosp" csv:"hosp"`
	Vent                     string `json:"vent" csv:"vent"`
	Icu                      string `json:"icu" csv:"icu"`
	Severe                   string `json:"severe" csv:"severe"`
	Population               string `json:"population" csv:"population"`
	AdministrativeAreaLevel  string `json:"administrative_area_level" csv:"administrative_area_level"`
	AdministrativeAreaLevel1 string `json:"administrative_area_level_1" csv:"administrative_area_level_1"`
	AdministrativeAreaLevel2 string `json:"administrative_area_level_2" csv:"administrative_area_level_2"`
	JisCode                  string `json:"jis_code" csv:"jis_code"`
}
